-
  name: 'Donation'
  uriPattern: 'donations/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Donation'
    '@action': 'list'  # Default action
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'list'

-
  name: 'Donation Code'
  uriPattern: 'donation-code/{@action}/{code}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'DonationCode'
    '@action': 'validate'
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'validate'
    'code':
      type: 'Text'
      defaultValue: ''


-
  name: 'Organization details'
  uriPattern: 'organization/view/{identifier}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Organization'
    '@action': 'view'
  routeParts:
    'identifier':
      type: 'Neos\Flow\Mvc\Routing\DynamicRoutePart'


-
  name: 'Organizations'
  uriPattern: 'organizations/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Organization'
    '@action': 'list'  # default action
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'list'