-
  name: 'Donation'
  uriPattern: 'donations/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Donation'
    '@action': 'list'  # Default action
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'list'

-
  name: 'Donation Code'
  uriPattern: 'donation-code/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'DonationCode'
    '@action': 'validate'
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'validate'
    'code':
      type: 'Text'
      defaultValue: ''


-
  name: 'Organization details'
  uriPattern: 'organization/view/{identifier}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Organization'
    '@action': 'view'
  routeParts:
    'identifier':
      type: 'Neos\Flow\Mvc\Routing\DynamicRoutePart'


-
  name: 'Organizations'
  uriPattern: 'organizations/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Organization'
    '@action': 'list'  # default action
  routeParts:
    '@action':
      type: 'Neos\Flow\Mvc\Routing\DynamicActionRoutePart'
      defaultValue: 'list'

- name: 'Custom-Page'
  uriPattern: 'custom'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Frontend'
    '@action': 'custom'
  routeValues:
    '@action': 'custom'
  _reverse: 'simple'

- name: 'start-page'
  uriPattern: 'start'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Start'
    '@action': 'validate'
  
- name: 'orgnizations-list-page'
  uriPattern: 'org/{@action}'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Org'
    '@action': 'list'

- name: 'imprint page'
  uriPattern: 'imprint'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Imprint'
    '@action': 'imprint'
  
- name: 'evaluation data'
  uriPattern: 'evaluation'
  defaults:
    '@package': 'SincNovation.Charity'
    '@controller': 'Evaluation'
    '@action': 'evaluation'