SincNovation:
  Charity:
    organizations:
      - id: 1
        name: "DKMS"
        imageUrl: "path/to/image1.jpg"
        description: "Unterstützung von Knochenmarkspenden Supporting bone marrow donation"
        link: "https://www.dkms.de/"
      - id: 2
        name: "Organization Two"
        imageUrl: "path/to/image2.jpg"
        description: "Description for Organization Two"
        link: "http://example.com/two"